version: '2.3'

services:
  app-1:
    container_name: node-nginx-1
    build: ./
    #image: node-nginx:latest
    ports:
      - 3000
    volumes:
      - ./app:/app

  app-2:
    container_name: node-nginx-2
    build: ./
    #image: node-nginx:latest
    ports:
      - 3000
    volumes:
      - ./app:/app

  nginx:
    container_name: nginx-app
    #build: ./nginx/
    image: nginx-app:latest
    links:
      - app-1:app-1
      - app-2:app-2
    ports:
      - 3000:80
    depends_on:
      - app-1
      - app-2
