version: '3.0'

services:
  app-1:
    container_name: node-nginx-1
    build: ./
    #image: node-nginx:latest
    ports:
      - 3000
    volumes:
      - ./app:/app

  app-2:
    container_name: node-nginx-2
    build: ./
    #image: node-nginx:latest
    ports:
      - 3000
    volumes:
      - ./app:/app

  nginx:
    container_name: nginx-app
    #build: ./nginx/
    image: nginx-app:latest
    links:
      - app-1:app-1
      - app-2:app-2
      - mongodb:mongodb
    ports:
      - 3000:80
    depends_on:
      - app-1
      - app-2
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null 
