version: '3.7'

services:
  app-1:
    container_name: node-nginx-1
    build: ./
    #image: node-nginx:latest
    ports:
      - 4000
    volumes:
      - ./app:/app
    links:
     - mongodb:mongodb
    depends_on:
      - mongodb
    environment:
     - MONGODB_URI='mongodb://mongodb:27017/'

  app-2:
    container_name: node-nginx-2
    build: ./
    #image: node-nginx:latest
    ports:
      - 4000
    volumes:
      - ./app:/app
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI='mongodb://mongodb:27017/admin"

  nginx:
    container_name: nginx-app
    #build: ./nginx/
    image: nginx-app:latest
    links:
      - app-1:app-1
      - app-2:app-2
      - mongodb:mongodb
    ports:
      - 4000:80
    depends_on:
      - app-1
      - app-2
      - mongodb

  
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./data/db:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    command: mongod --auth --bind_ip_all

#mongo command is mongo -u "admin" -p "pass" leekt.page:27017/admin --authenticationDatabase "admin"

#--config /data/db/mongod.conf  사용안하기로
#--authenticationDatabase admin --logpath=/dev/null 
